const taskManager = new TaskManager();
const save = document.getElementById("save");
const taskName = document.getElementById("name");
const description = document.getElementById("description");
const assignedTo = document.getElementById("assignedTo");
const dueDate = document.getElementById("dueDate");
const status = document.getElementById("status");
const email = document.getElementById("email");
save.onclick = taskManager.addTask(taskName.value, description.value, assignedTo.value, dueDate.value, status.value, email.value);
taskManager.render();